spring:
  application:
    name: jarvis-finance
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cloud:
    aws:
      sns:
        region: us-east-1

management:
  endpoints:
    web:
      exposure:
        include: '*'

# SNS topics and SQS queues
jarvis:
  finance:
    aws:
      sqs:
        queue:
          asset-changed: https://sqs.us-east-1.amazonaws.com/851725329993/asset-changed-queue

